---
type: showroom
tabs:
 - name: Terminal 3
   # secondary_name: Terminal 2
   type: 'terminal'
 - name: Codeserver
   type: 'codeserver'
 - name: Jupyter Lab
   port: '9443'
   path: '/'
 - name: Llamastack Docs
   url: 'https://llama-stack.readthedocs.io/en/latest/'
 - name: google
   url: 'https://google.com'
